services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    # Set environment variables directly in the docker-compose file
    #    environment:
    #      ENV_VARIABLE: ${ENV_VARIABLE}
    #      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    #    env_file:
    #      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    environment:
      - ANILIST_DOMAIN=${ANILIST_DOMAIN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - ANILIST_GRAPHQL=${ANILIST_GRAPHQL}
      - APP_URL=${APP_URL}

    env_file:
      - .env
  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
